### ISSUE TITLE
All in One 安装后，host服务启动失败

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/docs#110]
通过ansible安装部署后，host服务启动失败
![image](https://user-images.githubusercontent.com/32036395/101324745-aee5ff00-38a5-11eb-99f6-9f4f76dfd32c.png)
具体原因如下
[I 201207 07:52:47 guestman.(*SGuestManager).OnLoadExistingGuestsComplete(guestman.go:196)] Load existing guests complete...
[F 201207 07:52:47 hostinfo.(*SHostInfo).PutHostOnline(hostinfo.go:1112)] Can't put host online, unless resolve these problem map[openvswitch:kernel module openvswitch paramters version not found, is kernel version correct ??]

**Comment by zexi** [comment]
这个重启一次会好吗？

**Comment by zexi** [comment]
验证过，重启一次能解决这个问题。
原因是新安装的时候会替换 openvswitch 需要的内核，重启一次切换内核就行。
