### ISSUE TITLE
文档 安装部署 添加计算节点

### ISSUE THREAD

**Issue by lishiyucn** [yunionio/docs#1370]
控制节点是x86架构的centos，如果想添加 arm arrch64架构的计算节点，使用debain10的系统，可以正常的添加吗

**Comment by lishiyucn** [comment]
如果安装现在不支持的操作系统，自己怎么去按步骤安装？
比如安装银河麒麟v10,Debain11? 如果有具体的步骤，我可以尝试自己安装，成功之后贡献给社区

**Comment by lishiyucn** [comment]
使用版本 3.9.8 
控制节点x86 Centos7 添加计算节点 Arm Debain11 
执行命令时报错 -> ./run-in-docker.sh add-node 192.168.1.201 192.168.1.199
TASK [Gathering Facts] *********************************************************
ok: [192.168.1.199]

TASK [utils/detect-os : gather os specific variables] **************************
fatal: [192.168.1.199]: FAILED! => {"msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}

**Comment by lishiyucn** [comment]
ARM版本，如果要使用统信UOS，是需要统信UOS专业版哪个版本？ 看文档中只说了统信没有说具体的版本

**Comment by zexi** [comment]
重复问题 https://github.com/yunionio/cloudpods/issues/16479
