### ISSUE TITLE
配置环境

### ISSUE THREAD

**Issue by sacus** [yunionio/docs#16]
安装keepalived的主机节点是要用物理机吗？如果用aliyun ecs，我记得好像是vip不可用的。

**Comment by zexi** [comment]
我还没有在 aliyun 的虚拟机部署过，如果 vip 不可用的话，可以尝试直接使用 aliyun 的负载均衡实列替代 keepalived 和 haproxy 。
负载均衡的后端配置为 3 台运行 kubernetes 的 ecs 虚拟机，服务端口为 6443。
