### ISSUE TITLE
切换到企业版后，把常见问题的命令放到上面切换操作中

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/docs#177]
# 切换到企业版
$ ocadm cluster update --use-ee --wait
执行这个命令后
还需要执行，常见问题下面的两条命令，建议把 这两条命令放到上面

**Comment by zexi** [comment]
放到前面也不行，这个有时序问题。必须等 --use-ee/ce 切换完了过后，然后 delete configmap 才行。
