### ISSUE TITLE
ucloud的对接文档需要更新

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/docs#204]
UCloud官网已经更新， 个人中心已经找不到 API 密钥
新的入口在  
https://console.ucloud.cn/uapi/apikey
![image](https://user-images.githubusercontent.com/32036395/118808550-37001400-b8dc-11eb-82da-4baeb7924a47.png)

**Comment by hoganlxj** [comment]
![image](https://user-images.githubusercontent.com/32036395/118808819-79295580-b8dc-11eb-8105-49722d5ff0f6.png)
改为
AdministratorAccess   超级管理员权限

**Comment by zexi** [comment]
Fixes: https://github.com/yunionio/docs/pull/209
