### ISSUE TITLE
3.3开源版，s3存储桶上传文件失败

### ISSUE THREAD

**Issue by wanghaifeng-yuntuteng** [yunionio/docs#69]
class: "UnclassifiedError", code: 500,…}
class: "UnclassifiedError"
code: 500
data: {fields: [], id: "found module by s3uploads: No such module s3uploads for version v1"}
fields: []
id: "found module by s3uploads: No such module s3uploads for version v1"
details: "found module by s3uploads: No such module s3uploads for version v1"

**Comment by zexi** [comment]
已经解决
/close
