### ISSUE TITLE
All in One 安装 配置 ssh 免密登录 应该是copy 公钥

### ISSUE THREAD

**Issue by lengband** [yunionio/docs#70]
# 将生成的 ~/.ssh/id_rsa 拷贝到待部署机器
$ ssh-copy-id -i ~/.ssh/id_rsa root@10.168.26.216

改成

# 将生成的 ~/.ssh/id_rsa 拷贝到待部署机器
$ ssh-copy-id -i ~/.ssh/id_rsa.pub root@10.168.26.216

**Comment by zexi** [comment]
已经修复，多谢。
